
multicategoryList = {
    "1466": {"variant": ["Badges", "Clothing Pins"], "name": "Badges and Clothing Pins"},
    "1311": {"variant": ["Bath Gels", "Shower Gels"], "name": "Bath / Shower Gels"},
    "232": {"variant": ["BB Creams", "CC Creams"], "name": "BB & CC Cream"},
    "8398": {"variant": ["BB Creams", "CC Creams"], "name": "BB & CC Creams"},
    "2086": {"variant": ["Beard Care", "Moustache Care"], "name": "Beard & Moustache Care"},
    "2604": {"variant": ["Beard Care", "Moustache Care"], "name": "Beard & Moustache Care"},
    "970": {"variant": ["Body Mist", "Body Spray"], "name": "Body Mist/Spray"},
    "1386": {"variant": ["Body Scrubbers", "Body Brushes"], "name": "Body Scrubbers & Brushes"},
    "4366":	{"variant":["Bracelets", "Bangles"],"name":"Bracelets and Bangles"},
    "3109": {"variant": ["Bridal", "Sexy"], "name": "Bridal / Sexy"},
    "3083": {"variant": ["Brief", "Hipster"], "name": "Brief / Hipster"},
    "3101": {"variant": ["Camis", "Tops"], "name": "Camis / Tops"},
    "4395":	{"variant":["Candles", "Diffusers"], "name":"Candles and Diffusers"},
    "4377": {"variant": ["Cards", "Envelopes"], "name": "Cards and Envelopes"},
    "563": {"variant": ["Chains", "Waist Chains"], "name": "Chains and Waist Chains"},
    "1324": {"variant": ["Colognes", "Perfumes"], "name": "Colognes & Perfumes (EDT & EDP)"},
    "1647": {"variant": ["Cotton Buds", "Cotton Balls"], "name": "Cotton Buds and Balls"},
    "1675": {"variant": ["Cotton Buds", "Cotton Balls", "Cotton Wipes"], "name": "Cotton Buds, Balls & Wipes"},
    "1676": {"variant": ["Baby Creams", "Baby Lotions", "Baby Oils"], "name": "Creams, Lotions & Oils"},
    "1411": {"variant": ["Curling Irons", "Hair Stylers"], "name": "Curling Irons/Stylers"},
    "377": {"variant": ["Deodorants", "Roll Ons"], "name": "Deodorants/Roll-Ons"},
    "971": {"variant": ["Deodorants", "Roll Ons"], "name": "Deodorants/Roll-Ons"},
    "979": {"variant": ["Deodorants", "Roll Ons"], "name": "Deodorants/Roll-ons"},
    "1323": {"variant": ["Deodorants", "Roll Ons"], "name": "Deodorants/Roll-ons"},
    "362": {"variant": ["Hair Dryers", "Hair Stylers"], "name": "Dryers & Stylers"},
    "7562": {"variant": ["Face Care", "Body Care"], "name": "Face & Body Care"},
    "8400":	{"variant":["Face Masks", "Masks & Peels"],"name":"Masks & Peels"},
    "8397": {"variant":["Face Serum","Serums & Essence"],"name":"Serums & Essence"},
    "8394": {"variant": ["Face Moisturizer", "Day Cream"], "name": "Face Moisturizer & Day Cream"},
    "290": {"variant": ["Floss", "Tongue Cleaners"], "name": "Floss & Tongue Cleaners"},
    "331": {"variant": ["Hair Gels", "Hair Waxes"], "name": "Gels & Waxes"},
    "4386": {"variant": ["Gift Bags", "Gift Boxes"], "name": "Gift Bags and Boxes"},
    "2041": {"variant": ["Hair Creams", "Hair Masks"], "name": "Hair Creams & Masks"},
    "1298":	{"variant":["Hair Oil"],"name":"Hair Oils"},
    "364":	{"variant":["Hair Straighteners"],"name":"Straighteners"},
    "583": {"variant": ["Hand Creams", "Foot Creams"], "name": "Hand & Foot Creams"},
    "8434":	{"variant":	["Hand Masks", "Foot Masks"],"name":"Hand & Foot Masks"},
    "3095":	{"variant":["Jackets", "Hoodies"],"name":"Jackets & Hoodies"},
    "1483":	{"variant":["Laptop Bags","Laptop Sleeves"],"name":"Laptop Bags and Sleeves"},
    "3094": {"variant": ["Leggings", "Pants"], "name": "Leggings / Pants"},
    "6909": {"variant": ["Lens Solution", "Lens Accessories"], "name": "Lens Solution & Accessories"},
    "396":  {"variant": ["Loofahs", "Sponges"], "name": "Loofahs & Sponges"},
    "371":  {"variant":	["Body Lotions", "Body Creams"], "name": "Lotions & Creams"},
    "8420":  {"variant": ["Body Lotions", "Body Creams"], "name": "Lotions & Creams"},
    "4397": {"variant": ["Makeup Pouches", "Vanity Kits"], "name": "Makeup Pouches and Vanity Kits"},
    "3277": {"variant": ["Manicure Kits", "Pedicure Kits"], "name": "Manicure & Pedicure Kits"},
    "688": {"variant": ["Manicure Kits", "Pedicure Kits"], "name": "Manicure & Pedicure Kits"},
    "529": {"variant": ["Face Masks", "Masks & Peels"], "name": "Masks & Peels"},
    "1303": {"variant": ["Face Masks", "Masks & Peels"], "name": "Masks & Peels"},
    "554": {"variant": ["Massage Oils", "Carrier Oils"], "name": "Massage / Carrier Oils"},
    "4376": {"variant": ["Notebooks", "Notepads", "Folders"], "name": "Notebooks, Notepads and Folders"},
    "974": {"variant": ["Perfumes"], "name": "Perfumes (EDT & EDP)"},
    "962": {"variant": ["Perfumes"], "name": "Perfumes (EDT & EDP)"},
    "1290": {"variant": ["Pre Shaves", "Post Shaves"], "name": "Pre & Post Shaves"},
    "1410": {"variant": ["Pre Shaves", "Post Shaves"], "name": "Pre & Post Shaves"},
    "1287": {"variant": ["Razors", "Cartridges"], "name": "Razors & Cartridges"},
    "1398": {"variant": ["Razors", "Cartridges"], "name": "Razors & Cartridges"},
    "363": {"variant": ["Hair Rollers", "Hair Curlers"], "name": "Rollers & Curlers"},
    "3115": {"variant": ["Sarongs", "Cover-ups"], "name": "Sarongs & Cover-ups"},
    "369": {"variant": ["Scrubs", "Exfoliants"], "name": "Scrubs & Exfoliants"},
    "530": {"variant": ["Scrubs", "Exfoliators"], "name": "Scrubs & Exfoliators"},
    "8381":	{"variant":["Scrubs","Exfoliators"],"name":"Scrubs & Exfoliators"},
    "1304": {"variant": ["Scrubs", "Exfoliators"], "name": "Scrubs & Exfoliators"},
    "545":	{"variant":["Hair Serum"],"name":"Serum"},
    "7138": {"variant": ["Shaping Camis", "Shaping Slips"], "name": "Shaping Camis & Slips"},
    "1288": {"variant": ["Shavers", "Trimmers"], "name": "Shavers & Trimmers"},
    "2085": {"variant": ["Shavers", "Trimmers"], "name": "Shavers & Trimmers"},
    "39": {"variant": ["Shaving", "Hair Removal"], "name": "Shaving & Hair Removal"},
    "1553": {"variant": ["Shaving Creams", "Shaving Foams", "Shaving Gels"], "name": "Shaving Cream, Foams & Gels"},
    "1289": {"variant": ["Shaving Creams", "Shaving Foams", "Shaving Gels"], "name": "Shaving Creams, Foams & Gels"},
    "1484": {"variant": ["Shopping Bags", "Shopping Totes"], "name": "Shopping Bags and Totes"},
    "368": {"variant": ["Shower Gels", "Body Wash"], "name": "Shower Gels & Body Wash"},
    "8426":	{"variant":["Shower Gels","Body Wash"],"name":"Shower Gels & Body Wash"},
    "271": {"variant": ["Sponges", "Applicators"], "name": "Sponges & Applicators"},
    "3092": {"variant": ["Tanks", "Tees"], "name": "Tanks & Tees"},
    "746": {"variant": ["Teeth Care", "Dental Care"], "name": "Teeth & Dental Care"},
    "8392":	{"variant":["Toner"],"name":"Toners & Mists"},
    "1481": {"variant": ["Travel Bags", "Backpacks"], "name": "Travel Bags and Backpacks"},
    "4524": {"variant": ["Tummy Cinchers", "Waist Cinchers"], "name": "Tummy And Waist Cinchers"},
    "8403": {"variant": ["Under Eye Creams", "Under Eye Serums"], "name": "Under Eye Cream & Serums"},
    "3105": {"variant": ["Wraps", "Gowns"], "name": "Wraps / Gowns"},
  }


def getVariants(id):
    global multicategoryList
    if id in multicategoryList:
      return multicategoryList[id]['variant']
    return None

if __name__ == '__main__':
    print(getVariants("7291"))