
multicategoryList = {
    "1676": {"variant": ["Baby Creams","Baby Lotions","Baby Oils"], "name": "Creams, Lotions & Oils"},
    "1466": {"variant": ["Badges","Clothing Pins"], "name": "Badges and Clothing Pins"},
    "1386": {"variant": ["Bath Brushes","Body Scrubbers"], "name": "Body Scrubbers & Brushes"},
    "1311": {"variant": ["Bath Gels","Shower Gels", "Body Wash"], "name": "Bath / Shower Gels"},
    "232": {"variant": ["BB Creams","CC Creams"], "name": "BB & CC Cream"},
    "8398": {"variant": ["BB Creams","CC Creams"], "name": "BB & CC Creams"},
    "2086": {"variant": ["Beard Care","Moustache Care"], "name": "Beard & Moustache Care"},
    "2604": {"variant": ["Beard Care","Moustache Care"], "name": "Beard & Moustache Care"},
    "371": {"variant": ["Body Lotions","Body Creams"], "name": "Lotions & Creams"},
    "8420": {"variant": ["Body Lotions","Body Creams"], "name": "Lotions & Creams"},
    "970": {"variant": ["Body Mist","Body Spray"], "name": "Body Mist/Spray"},
    "4366": {"variant": ["Bracelets","Bangles"], "name": "Bracelets and Bangles"},
    "3109": {"variant": ["Bridal","Sexy"], "name": "Bridal / Sexy"},
    "3083": {"variant": ["Brief","Hipster"], "name": "Brief / Hipster"},
    "3101": {"variant": ["Camisole", "Cami Tops"], "name": "Camis / Tops"},
    "3107": {"variant": ["Cotton Nighty","Nightdress"], "name": "Cotton"},
    "3108": {"variant": ["Satin Nighty","Satin Nightwear"], "name": "Satin"},
    "4395": {"variant": ["Candles","Diffusers"], "name": "Candles and Diffusers"},
    "4377": {"variant": ["Cards","Envelopes"], "name": "Cards and Envelopes"},
    "563": {"variant": ["Chains","Waist Chains"], "name": "Chains and Waist Chains"},
    "1324": {"variant": ["Colognes","Perfumes"], "name": "Colognes & Perfumes (EDT & EDP)"},
    "1647": {"variant": ["Cotton Buds","Cotton Balls"], "name": "Cotton Buds and Balls"},
    "1675": {"variant": ["Cotton Buds","Cotton Balls","Cotton Wipes"], "name": "Cotton Buds, Balls & Wipes"},
    "1411": {"variant": ["Curling Irons","Hair Stylers"], "name": "Curling Irons/Stylers"},
    "1323": {"variant": ["Deodorants","Roll Ons"], "name": "Deodorants/Roll-ons"},
    "377": {"variant": ["Deodorants","Roll Ons"], "name": "Deodorants/Roll-Ons"},
    "971": {"variant": ["Deodorants","Roll Ons"], "name": "Deodorants/Roll-Ons"},
    "979": {"variant": ["Deodorants","Roll Ons"], "name": "Deodorants/Roll-ons"},
    "7562": {"variant": ["Face Care","Body Care"], "name": "Face & Body Care"},
    "1303": {"variant": ["Face Masks","Masks & Peels"], "name": "Masks & Peels"},
    "529": {"variant": ["Face Masks","Masks & Peels"], "name": "Masks & Peels"},
    "8400": {"variant": ["Face Masks","Masks & Peels"], "name": "Masks & Peels"},
    "13561": {"variant": ["Face Masks"], "name": "Face Mask"},
    "8394": {"variant": ["Face Moisturizer","Day Cream"], "name": "Face Moisturizer & Day Cream"},
    "8397": {"variant": ["Face Serum","Serums"], "name": "Serums & Essence"},
    "290": {"variant": ["Floss","Tongue Cleaners"], "name": "Floss & Tongue Cleaners"},
    "4386": {"variant": ["Gift Bags","Gift Boxes"], "name": "Gift Bags and Boxes"},
    "2041": {"variant": ["Hair Creams","Hair Masks"], "name": "Hair Creams & Masks"},
    "362": {"variant": ["Hair Dryers","Hair Stylers"], "name": "Dryers & Stylers"},
    "331": {"variant": ["Hair Gels","Hair Waxes"], "name": "Gels & Waxes"},
    "1298": {"variant": ["Hair Oil"], "name": "Hair Oils"},
    "363": {"variant": ["Hair Rollers","Hair Curlers"], "name": "Rollers & Curlers"},
    "545": {"variant": ["Hair Serum", "Serums"], "name": "Serum"},
    "320": {"variant": ["Hair Serum", "Serums"], "name": "Hair Serum"},
    "364": {"variant": ["Hair Straighteners"], "name": "Straighteners"},
    "583": {"variant": ["Hand Creams","Foot Creams"], "name": "Hand & Foot Creams"},
    "8434": {"variant": ["Hand Masks","Foot Masks"], "name": "Hand & Foot Masks"},
    "9610": {"variant": ["Bath Salts", "Bath Bombs"], "name": "Bath Salts & Bath Bombs"},
    "3048": {"variant": ["Lingerie"], "name": "Lingerie & More"},
    "9581": {"variant": ["Masks & Peels","Face Masks"], "name": "Masks & Peels"},
    "3095": {"variant": ["Jackets","Hoodies"], "name": "Jackets & Hoodies"},
    "3098": {"variant": ["Babydoll Nightwear"], "name": "Babydoll"},
    "1483": {"variant": ["Laptop Bags","Laptop Sleeves"], "name": "Laptop Bags and Sleeves"},
    "3094": {"variant": ["Leggings","Pants"], "name": "Leggings / Pants"},
    "6909": {"variant": ["Lens Solution","Lens Accessories"], "name": "Lens Solution & Accessories"},
    "396": {"variant": ["Loofahs","Sponges"], "name": "Loofahs & Sponges"},
    "4397": {"variant": ["Makeup Pouches","Vanity Kits"], "name": "Makeup Pouches and Vanity Kits"},
    "3277": {"variant": ["Manicure Kits","Pedicure Kits"], "name": "Manicure & Pedicure Kits"},
    "688": {"variant": ["Manicure Kits","Pedicure Kits"], "name": "Manicure & Pedicure Kits"},
    "554": {"variant": ["Massage Oils","Carrier Oils"], "name": "Massage / Carrier Oils"},
    "4376": {"variant": ["Notebooks","Notepads","Folders"], "name": "Notebooks, Notepads and Folders"},
    "962": {"variant": ["Perfumes"], "name": "Perfumes (EDT & EDP)"},
    "974": {"variant": ["Perfumes"], "name": "Perfumes (EDT & EDP)"},
    "1290": {"variant": ["Pre Shaves","Post Shaves"], "name": "Pre & Post Shaves"},
    "1410": {"variant": ["Pre Shaves","Post Shaves"], "name": "Pre & Post Shaves"},
    "1287": {"variant": ["Razors & Cartridges","Cartridges"], "name": "Razors & Cartridges"},
    "1398": {"variant": ["Razors & Cartridges","Cartridges"], "name": "Razors & Cartridges"},
    "369": {"variant": ["Scrubs","Exfoliants"], "name": "Scrubs & Exfoliants"},
    "1304": {"variant": ["Scrubs","Exfoliators"], "name": "Scrubs & Exfoliators"},
    "530": {"variant": ["Scrubs","Exfoliators"], "name": "Scrubs & Exfoliators"},
    "8381": {"variant": ["Scrubs","Exfoliators"], "name": "Scrubs & Exfoliators"},
    "9582": {"variant": ["Scrubs", "Exfoliators"], "name": "Scrubs & Exfoliators"},
    "7138": {"variant": ["Shaping Camis"," Shaping Slips"], "name": "Shaping Camis & Slips"},
    "1288": {"variant": ["Shavers","Trimmers"], "name": "Shavers & Trimmers"},
    "2085": {"variant": ["Shavers","Trimmers"], "name": "Shavers & Trimmers"},
    "1553": {"variant": ["Shaving Creams","Shaving Foams","Shaving Gels"], "name": "Shaving Cream, Foams & Gels"},
    "1289": {"variant": ["Shaving Creams","Shaving Foams","Shaving Gels"], "name": "Shaving Creams, Foams & Gels"},
    "39": {"variant": ["Shaving","Hair Removal"], "name": "Shaving & Hair Removal"},
    "1484": {"variant": ["Shopping Bags","Shopping Totes"], "name": "Shopping Bags and Totes"},
    "368": {"variant": ["Shower Gels","Body Wash"], "name": "Shower Gels & Body Wash"},
    "8426": {"variant": ["Shower Gels","Body Wash"], "name": "Shower Gels & Body Wash"},
    "9606": {"variant": ["Shower Gels","Body Wash"], "name": "Shower Gels & Body Wash"},
    "7314": {"variant": ["Body Wash","Shower Gels"], "name": "Body Wash / Shower Gels"},
    "9592": {"variant": ["Foundation","Concealer"], "name": "Foundation & Concealer"},
    "9593": {"variant": ["Blush","Highlighter"], "name": "Blush & Highlighter"},
    "9591": {"variant": ["Lip Balm","Lip Gloss"], "name": "Lip Balm & Gloss"},
    "8427": {"variant": ["Bath Scrubs","Body Scrubs", "Scrubs"], "name": "Bath Scrubs"},
    "9409": {"variant": ["Body Scrubs", "Scrubs"], "name": "Body Scrubs"},
    "1313": {"variant": ["Body Scrubs", "Scrubs"], "name": "Body Scrubs"},
    "8429": {"variant": ["Face Sunscreen", "Sunscreen"], "name": "Face Sunscreen"},
    "8430": {"variant": ["Body Sunscreen", "Sunscreen"], "name": "Body Sunscreen"},
    "271": {"variant": ["Sponges","Applicators"], "name": "Sponges & Applicators"},
    "10134": {"variant": ["Heels","Wedges"], "name": "Heels & Wedges"},
    "746": {"variant": ["Teeth Care","Dental Care"], "name": "Teeth & Dental Care"},
    "8392": {"variant": ["Toner"], "name": "Toners & Mists"},
    "1481": {"variant": ["Travel Bags","Backpacks"], "name": "Travel Bags and Backpacks"},
    "4524": {"variant": ["Tummy Cinchers","Waist Cinchers"], "name": "Tummy And Waist Cinchers"},
    "8403": {"variant": ["Under Eye Cream","Under Eye Serums"], "name": "Under Eye Cream & Serums"},
    "3105": {"variant": ["Nightgowns"], "name": "Wraps / Gowns"},
    "6620": {"variant": ["Fiction Books"], "name": "Fiction"},
    "6621": {"variant": ["Non Fiction Books"], "name": "Non Fiction"},
    "3092": {"variant": ["Tank Tops","Tshirts"], "name": "Tanks & Tees"},
    "3069": {"variant": ["Demi / Balconette Bra"], "name": "Demi / Balconette"},
    "4518": {"variant": ["Designer Backs Bra"], "name": "Designer Backs"},
    "3070": {"variant": ["Full Coverage Bra"], "name": "Full"},
    "3062": {"variant": ["Multiway Bra"], "name": "Multiway"},
    "5452": {"variant": ["Non-Padded Bra"], "name": "Non-Padded"},
    "3067": {"variant": ["Padded Bra"], "name": "Padded"},
    "3061": {"variant": ["Push-up Bra"], "name": "Push-up"},
    "3068": {"variant": ["Racerback Bra"], "name": "Racerback"},
    "3066": {"variant": ["Strapless Bra"], "name": "Strapless"},
    "3060": {"variant": ["T-Shirt Bra"], "name": "T-Shirt"},
    "3065": {"variant": ["Underwired Bra"], "name": "Underwired"},
    "3063": {"variant": ["Unlined Bra"], "name": "Unlined"},
    "3064": {"variant": ["Wireless Bra"], "name": "Wireless"},
    "4520": {"variant": ["BACKLESS Bra"], "name": "BACKLESS"},
    "4521": {"variant": ["Basics Bra"], "name": "Basics"},
    "3076": {"variant": ["Beginners Bra"], "name": "Beginners"},
    "3075": {"variant": ["Bridal Bra"], "name": "Bridal"},
    "3071": {"variant": ["Cotton Bra"], "name": "Cotton"},
    "6043": {"variant": ["High Coverage Bra"], "name": "High Coverage"},
    "3073": {"variant": ["Lace Bra"], "name": "Lace"},
    "6039": {"variant": ["Lightly Lined Bra"], "name": "Lightly Lined"},
    "6041": {"variant": ["Low Coverage Bra"], "name": "Low Coverage"},
    "3074": {"variant": ["Maternity Bra"], "name": "Maternity"},
    "6042": {"variant": ["Medium Coverage Bra"], "name": "Medium Coverage"},
    "4531": {"variant": ["Plus Size Bra"], "name": "Plus Size"},
    "3072": {"variant": ["Sexy Bra"], "name": "Sexy"},
    "5779": {"variant": ["Camisoles","Slips & Camisoles"], "name": "Slips & Camisoles"},
    "8251": {"variant": ["Lingerie Socks"], "name": "Socks"},
    "3055": {"variant": ["Lingerie Value Packs"], "name": "Value Packs"},
    "3111": {"variant": ["One Piece Swimwear"], "name": "One Piece"},
    "3115": {"variant": ["Sarongs"], "name": "Sarongs & Cover-ups"},
    "3089": {"variant": ["Bridal Underwear"], "name": "Bridal"},
    "3087": {"variant": ["Cotton Underwear"], "name": "Cotton"},
    "3081": {"variant": ["Lace Underwear"], "name": "Lace"},
    "3082": {"variant": ["Seamless Underwear"], "name": "Seamless"},
    "3090": {"variant": ["Sexy Underwear"], "name": "Sexy"},
    "8379": {"variant": ["Facewash", "Face Wash"], "name": "Face Wash"},
    "263": {"variant": ["Liquid Lipstick", "Lipstick"], "name": "Liquid Lipstick"},
    "9566": {"variant": ["Facewash", "Face Wash"], "name": "Face Wash"},
    "1654": {"variant": ["Intimate Care"], "name": "Intimate Hygiene"},
    "9598": {"variant": ["Shampoo", "Hair Cleanser"], "name": "Shampoo & Cleanser"},
    "9579": {"variant": ["Face Serum","Serums"], "name": "Serums"},
    "14175": {"variant": ["Bhaiya Bhabi Rakhis","Rakhis"], "name": "Bhaiya Bhabi Rakhis"},
    "14029": {"variant": ["Bluetooth Headphones"], "name": "Bluetooth"},
    "14181": {"variant": ["Bracelet Rakhis","Rakhis"], "name": "Bracelet Rakhis"},
    "6046": {"variant": ["Brief Sets","Brief"], "name": "Brief Sets"},
    "1464": {"variant": ["Jewellery Sets","Jewellery"], "name": "Jewellery Sets"},
    "14191": {"variant": ["Quirky Rakhis","Rakhis"], "name": "Quirky Rakhis"},
    "14174": {"variant": ["Rakhi Sets","Rakhi"], "name": "Rakhi Sets"},
    "1408": {"variant": ["Hair Straighteners"], "name": "Straighteners"},
    "13791": {"variant": ["Bra Value Packs"], "name": "Value Packs"},
    "14028": {"variant": ["Wired Headphones"], "name": "Wired"},
    "3056": {"variant": ["Sleepwear","Loungewear"], "name": "Sleep & Lounge"}
  }


def getVariants(id):
    global multicategoryList
    if id in multicategoryList:
      return multicategoryList[id]['variant']
    return None

if __name__ == '__main__':
    print(getVariants("7291"))